### ISSUE TITLE
Make the website look better

### ISSUE THREAD

**Issue by xymostech** [xymostech/gdq-schedule#1]
I'm really bad at design. Making the site look better at all would be great! Maybe we could use the GDQ color scheme too, to keep it on-brand (if we're allowed to do that?)

**Comment by JettBurns14** [comment]
Hi Emily, I can help with this specific issue, and have a design in mind! With a few modifications, I think [this](https://i.pinimg.com/originals/23/38/f0/2338f016b0cb65670f0da28a731f455f.jpg) general layout and style could be easily achieved. Thoughts? =)

**Comment by xymostech** [comment]
That would look good to me! Feel free to send PRs!

**Comment by JettBurns14** [comment]
Should this be closed?

**Comment by xymostech** [comment]
Yup! It looks great now!
